services:
  frontend:
    build:
      context: .
      dockerfile: apps/excelidraw-frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_HTTP_BACKEND_URL=https://drawsync.space/api
      - NEXT_PUBLIC_WS_BACKEND_URL=wss://drawsync.space/ws
    restart: unless-stopped

  http-backend:
    build:
      context: .
      dockerfile: apps/http-backned/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  ws-backend:
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - frontend
      - http-backend
      - ws-backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
